version: '3'

services:

  go-base:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-base:0.1
    container_name: go-base

  start-server:
    image: go-base:0.1
    container_name: jp-word-extractor-server
    ports:
      - "8081:8081"
    environment:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
      GO111MODULE: "on"
    working_dir: /go-server
    volumes:
      - .:/go-server
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache # mount local modules cache to speed up build process
    command: /bin/sh -c "chmod o+x start_server.sh && ./start_server.sh"
    depends_on:
      - go-base

  server-tests:
    image: go-base:0.1
    volumes:
      - .:/go-server
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache # mount local modules cache to speed up build process
    working_dir: /go-server
    environment:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
      GO111MODULE: "on"
    command: /bin/sh -c "chmod o+x run_tests.sh && ./run_tests.sh"
    depends_on:
      - go-base